/**
 * expenseMatrix.js
 * @author CloudPact Technologies
 * @description : This script is used giving value based on income level,citytier and needs
 **/
var expenseMatrix_json=[
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buying a House",
    "": "MediumTier I/MetroBuying a House",
    "Single": "",
    "Married": "1",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Buying a House",
    "": "MediumTier IIBuying a House",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Buying a House",
    "": "MediumTier IIIBuying a House",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buying a House",
    "": "HighTier I/MetroBuying a House",
    "Single": "",
    "Married": "1",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Buying a House",
    "": "HighTier IIBuying a House",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Buying a House",
    "": "HighTier IIIBuying a House",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buying a House",
    "": "LowTier I/MetroBuying a House",
    "Single": "",
    "Married": "1",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Buying a House",
    "": "LowTier IIBuying a House",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Buying a House",
    "": "LowTier IIIBuying a House",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "MediumTier I/MetroChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "MediumTier IIChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "MediumTier IIIChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "HighTier I/MetroChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "900000",
    "Married with grown up child": "900000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "HighTier IIChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "HighTier IIIChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "LowTier I/MetroChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "LowTier IIChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "LowTier IIIChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Marriage",
    "": "MediumTier I/MetroChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "2.25",
    "Nearing Retirement": "2.25",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Child's Marriage",
    "": "MediumTier IIChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "1.5",
    "Nearing Retirement": "1.5",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Child's Marriage",
    "": "MediumTier IIIChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "1.5",
    "Nearing Retirement": "1.5",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Marriage",
    "": "HighTier I/MetroChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "2.5",
    "Nearing Retirement": "2.5",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Child's Marriage",
    "": "HighTier IIChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "2",
    "Nearing Retirement": "2",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Child's Marriage",
    "": "HighTier IIIChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "2",
    "Nearing Retirement": "2",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Marriage",
    "": "LowTier I/MetroChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "2",
    "Nearing Retirement": "2",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Child's Marriage",
    "": "LowTier IIChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "1.333333333",
    "Nearing Retirement": "1.333333333",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Child's Marriage",
    "": "LowTier IIIChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "1.333333333",
    "Nearing Retirement": "1.333333333",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Health -Family",
    "": "MediumTier I/MetroHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Health -Family",
    "": "MediumTier IIHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Health -Family",
    "": "MediumTier IIIHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Health -Family",
    "": "HighTier I/MetroHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Health -Family",
    "": "HighTier IIHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Health -Family",
    "": "HighTier IIIHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Health -Family",
    "": "LowTier I/MetroHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Health -Family",
    "": "LowTier IIHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Health -Family",
    "": "LowTier IIIHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Legacy",
    "": "MediumTier I/MetroLegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Legacy",
    "": "MediumTier IILegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Legacy",
    "": "MediumTier IIILegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Legacy",
    "": "HighTier I/MetroLegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Legacy",
    "": "HighTier IILegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Legacy",
    "": "HighTier IIILegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Legacy",
    "": "LowTier I/MetroLegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Legacy",
    "": "LowTier IILegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Legacy",
    "": "LowTier IIILegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Liquidity",
    "": "MediumTier I/MetroLiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Liquidity",
    "": "MediumTier IILiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Liquidity",
    "": "MediumTier IIILiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Liquidity",
    "": "HighTier I/MetroLiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Liquidity",
    "": "HighTier IILiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Liquidity",
    "": "HighTier IIILiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Liquidity",
    "": "LowTier I/MetroLiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Liquidity",
    "": "LowTier IILiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Liquidity",
    "": "LowTier IIILiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Living Expenses",
    "": "MediumTier I/MetroLiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Living Expenses",
    "": "MediumTier IILiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Living Expenses",
    "": "MediumTier IIILiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Living Expenses",
    "": "HighTier I/MetroLiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Living Expenses",
    "": "HighTier IILiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Living Expenses",
    "": "HighTier IIILiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Living Expenses",
    "": "LowTier I/MetroLiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Living Expenses",
    "": "LowTier IILiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Living Expenses",
    "": "LowTier IIILiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "MediumTier I/MetroBuy/Change Car",
    "Single": "0.18",
    "Married": "0.18",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "MediumTier IIBuy/Change Car",
    "Single": "",
    "Married": "0.18",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "MediumTier IIIBuy/Change Car",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "HighTier I/MetroBuy/Change Car",
    "Single": "0.18",
    "Married": "0.18",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "0.18",
    "Retiree": "0.18"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "HighTier IIBuy/Change Car",
    "Single": "0.18",
    "Married": "0.18",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "0.18",
    "Retiree": "0.18"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "HighTier IIIBuy/Change Car",
    "Single": "0.18",
    "Married": "0.18",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "0.18",
    "Retiree": "0.18"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "LowTier I/MetroBuy/Change Car",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "LowTier IIBuy/Change Car",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "LowTier IIIBuy/Change Car",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Renovation",
    "": "MediumTier I/MetroRenovation",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Renovation",
    "": "MediumTier IIRenovation",
    "Single": "0",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Renovation",
    "": "MediumTier IIIRenovation",
    "Single": "0",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Renovation",
    "": "HighTier I/MetroRenovation",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Renovation",
    "": "HighTier IIRenovation",
    "Single": "0",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Renovation",
    "": "HighTier IIIRenovation",
    "Single": "0",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Renovation",
    "": "LowTier I/MetroRenovation",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Renovation",
    "": "LowTier IIRenovation",
    "Single": "0",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Renovation",
    "": "LowTier IIIRenovation",
    "Single": "0",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Retirement",
    "": "MediumTier I/MetroRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Retirement",
    "": "MediumTier IIRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Retirement",
    "": "MediumTier IIIRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Retirement",
    "": "HighTier I/MetroRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Retirement",
    "": "HighTier IIRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Retirement",
    "": "HighTier IIIRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Retirement",
    "": "LowTier I/MetroRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Retirement",
    "": "LowTier IIRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Retirement",
    "": "LowTier IIIRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Second house",
    "": "MediumTier I/MetroSecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Second house",
    "": "MediumTier IISecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Second house",
    "": "MediumTier IIISecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Second house",
    "": "HighTier I/MetroSecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Second house",
    "": "HighTier IISecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Second house",
    "": "HighTier IIISecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Second house",
    "": "LowTier I/MetroSecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Second house",
    "": "LowTier IISecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Second house",
    "": "LowTier IIISecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "MediumTier I/MetroPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "MediumTier IIPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "MediumTier IIIPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "HighTier I/MetroPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "HighTier IIPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "HighTier IIIPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "LowTier I/MetroPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "LowTier IIPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "LowTier IIIPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Start-up Capital",
    "": "MediumTier I/MetroStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Start-up Capital",
    "": "MediumTier IIStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Start-up Capital",
    "": "MediumTier IIIStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Start-up Capital",
    "": "HighTier I/MetroStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Start-up Capital",
    "": "HighTier IIStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Start-up Capital",
    "": "HighTier IIIStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Start-up Capital",
    "": "LowTier I/MetroStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Start-up Capital",
    "": "LowTier IIStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Start-up Capital",
    "": "LowTier IIIStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "MediumTier I/MetroVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "Medium",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "MediumTier IIVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "Medium",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "MediumTier IIIVacation/Festivities",
    "Single": "",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "HighTier I/MetroVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "High",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "HighTier IIVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "High",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "HighTier IIIVacation/Festivities",
    "Single": "",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "Low",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "LowTier I/MetroVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "Low",
    "City Category": "Tier II",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "LowTier IIVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "Low",
    "City Category": "Tier III",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "LowTier IIIVacation/Festivities",
    "Single": "",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buying a House",
    "": "Medium to HighTier I/MetroBuying a House",
    "Single": "",
    "Married": "1",
    "Married with young kid/s": "1",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Higher Education",
    "": "Medium to HighTier I/MetroChild's Higher Education",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "600000",
    "Married with grown up child": "600000",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Child's Marriage",
    "": "Medium to HighTier I/MetroChild's Marriage",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "2.5",
    "Nearing Retirement": "2.5",
    "Retiree": "2.5"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Health -Family",
    "": "Medium to HighTier I/MetroHealth -Family",
    "Single": "0.06",
    "Married": "0.06",
    "Married with young kid/s": "0.06",
    "Married with growing kid/s": "0.06",
    "Married with grown up child": "0.06",
    "Nearing Retirement": "0.06",
    "Retiree": "0.12"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Legacy",
    "": "Medium to HighTier I/MetroLegacy",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Liquidity",
    "": "Medium to HighTier I/MetroLiquidity",
    "Single": "0.17",
    "Married": "0.17",
    "Married with young kid/s": "0.17",
    "Married with growing kid/s": "0.17",
    "Married with grown up child": "0.17",
    "Nearing Retirement": "0.17",
    "Retiree": "0.17"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Living Expenses",
    "": "Medium to HighTier I/MetroLiving Expenses",
    "Single": "0.5",
    "Married": "0.5",
    "Married with young kid/s": "0.5",
    "Married with growing kid/s": "0.5",
    "Married with grown up child": "0.5",
    "Nearing Retirement": "0.5",
    "Retiree": "0.5"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Buy/Change Car",
    "": "Medium to HighTier I/MetroBuy/Change Car",
    "Single": "0.18",
    "Married": "0.18",
    "Married with young kid/s": "0.18",
    "Married with growing kid/s": "0.18",
    "Married with grown up child": "0.18",
    "Nearing Retirement": "0.18",
    "Retiree": "0.18"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Renovation",
    "": "Medium to HighTier I/MetroRenovation",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "0",
    "Married with growing kid/s": "0",
    "Married with grown up child": "0",
    "Nearing Retirement": "0",
    "Retiree": "0"
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Retirement",
    "": "Medium to HighTier I/MetroRetirement",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "5.25",
    "Married with grown up child": "5.25",
    "Nearing Retirement": "5.25",
    "Retiree": ""
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Second house",
    "": "Medium to HighTier I/MetroSecond house",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "1",
    "Married with grown up child": "1",
    "Nearing Retirement": "1",
    "Retiree": ""
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Pure Protection Cover",
    "": "Medium to HighTier I/MetroPure Protection Cover",
    "Single": "20",
    "Married": "20",
    "Married with young kid/s": "20",
    "Married with growing kid/s": "20",
    "Married with grown up child": "20",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Start-up Capital",
    "": "Medium to HighTier I/MetroStart-up Capital",
    "Single": "",
    "Married": "",
    "Married with young kid/s": "",
    "Married with growing kid/s": "",
    "Married with grown up child": "",
    "Nearing Retirement": "",
    "Retiree": ""
},
{
    "Income Level": "Medium to High",
    "City Category": "Tier I/Metro",
    "Need/Expenses Revised": "Vacation/Festivities",
    "": "Medium to HighTier I/MetroVacation/Festivities",
    "Single": "0.1",
    "Married": "0.1",
    "Married with young kid/s": "0.1",
    "Married with growing kid/s": "0.1",
    "Married with grown up child": "0.1",
    "Nearing Retirement": "0.1",
    "Retiree": "0.21"
    }
];