/**
 * newDBColumns.js
 * @author CloudPact Technologies
 * @description : This script is used for altering the local table
 **/
var newDBObject = {
	"PDC_Customer_Details":[
		{"name" : "PIVC_Video_YN",							"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "LA_EKYC_Aadhar_YN",						"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "PR_EKYC_Aadhar_YN",						"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Super_Track_Login",						"datatype" : "VARCHAR",						"objdefault" :''}
	],
	"saveActivityPlanning":[
		{"name" : "Activity",									"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Activity_Date",								"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Activity_Id",								"datatype" : "NUMBER",		  				"objdefault" :''},
		{"name" : "Activity_Location",							"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Activity_Time",								"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Advisor_Status",								"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Address",									"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Added_By",									"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Device_Id",									"datatype" : "VARCHAR",	   					"objdefault" :''},
		{"name" : "Lead_Id",									"datatype" : "NUMBER ",		            	"objdefault" :null},
		{"name" : "Source_From",								"datatype" : "VARCHAR",						"objdefault" :''},
	    {"name" : "Special_Campaign",							"datatype" : "VARCHAR",						"objdefault" :''},
	    {"name" : "Latitude",									"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Longitude",				 					"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Sub_Activity",								"datatype" : "VARCHAR",						"objdefault" :''},
		{"name" : "Sub_Activity_Options",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "With_Whom",									"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "Name",										"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DOB",										"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "City",										"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "Gender",										"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "Income",										"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "Marital_Status",								"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "Sync_Txn_Id",								"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "issync",										"datatype" : "VARCHAR",						"objdefault" : '0'},
		{"name" : "iscompleted",								"datatype" : "VARCHAR",						"objdefault" : '0'},
		],
	"saveActivityResult":[
			{"name" : "Product_Update",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "R_n_R",										"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Claims_Record",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Fund_Performance",							"datatype" : "VARCHAR",						"objdefault" : ''},
		],
	"saveNewLead":[
			{"name" : "Aadhaar",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Added_By",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Address_1",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Address_2",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Address_3",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Address",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "City",										"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Commute_Time",								"datatype" : "VARCHAR",	   					"objdefault" :''},
			{"name" : "DOB",										"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Marital_Status",								"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Dependents",									"datatype" : "VARCHAR",						"objdefault" :''},
		    {"name" : "Device_Id",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Educational_Background",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Email_ID",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Gender",										"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Campaign",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Income",										"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Landline",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Category",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Id",									"datatype" : "NUMBER PRIMARY KEY",			"objdefault" : ''},
			{"name" : "Lead_Source",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Status",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Sub_Source",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Sub_Type",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Type",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Latitude",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Longitude",				 					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Mobile",										"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Name",										"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Occupation",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Pin_Code",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Source_From",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "State",										"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Reference_LeadID",							"datatype" : "NUMBER",						"objdefault" : '0'},
			{"name" : "Reference_YN",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Sync_Txn_Id",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "issync",										"datatype" : "VARCHAR",						"objdefault" : '0'},
			{"name" : "iscompleted",								"datatype" : "VARCHAR",						"objdefault" : '0'},
		],
		"inputPojo":[
			{"name" : "Activity_Id",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Added_Date",							"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Campaign",							"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Flag",								"datatype" : "NUMBER",						"objdefault" :''},
			{"name" : "Activity_Result_Id",					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "LeadTypeFlag",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Lead_Id",							"datatype" : "VARCHAR PRIMARY KEY",			"objdefault" :''},
			{"name" : "Lead_Sub_Source",					"datatype" : "VARCHAR",				   		"objdefault" : ''},
			{"name" : "Lead_Type",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Mobile",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Meeting_Status",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Name",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Sub_Activity",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Sub_Activity_Options",				"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Category",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "DOB",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "City",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Gender",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Income",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Marital_Status",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Aadhaar",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Commute_Time",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Dependents",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Educational_Background",				"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Landline",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Latitude",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Status",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Longitude",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Occupation",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Pin_Code",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Reference_LeadID",					"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Reference_YN",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Source_From",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "State",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Updated_By",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Updated_Date",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Address",						    "datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Alternate_Number",					"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Added_By",						    "datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Sub_Type",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Lead_Source",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Email_ID",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Device_Id",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Address_1",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Address_2",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Address_3",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "issync",								"datatype" : "VARCHAR",						"objdefault" : '0'},
			{"name" : "iscomplete",							"datatype" : "VARCHAR",						"objdefault" : '0'},
		],
		"Customer_Aadhar_Details":[
			{"name" : "Device_SN",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Device_PN",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Device_ModelNo",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Device_ModelName",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Device_Date",							"datatype" : "VARCHAR",						"objdefault" : ''},
		],
		"Expert_To_Call":[
			{"name" : "Txn_Id",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Lead_Id",								"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Activity_ID",							"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Activity_Result_Id",						"datatype" : "VARCHAR PRIMARY KEY",			"objdefault" :''},
			{"name" : "Name",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Gender",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "DOB",									"datatype" : "DATETIME",					"objdefault" :''},
			{"name" : "Occupation",								"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Income",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Mobile",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Alternate_Number",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Landline",								"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "State",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "City",									"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Pin_Code",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Email_ID",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image1",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image2",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image3",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image4",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image5",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image6",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Image7",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "LifePlanner_Pdf",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Added_By",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Added_Date",								"datatype" : "DATETIME",					"objdefault" : ''},
			{"name" : "Device_Id",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Source_From",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Marital_Status",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Updated_Date",							"datatype" : "DATETIME",					"objdefault" : ''},
			{"name" : "Updated_By",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Longitude",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Latitude",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Address",								"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "issync",									"datatype" : "VARCHAR",						"objdefault" : 0}	
		],
		"PDC_Video_Details":[
			{"name" : "Txn_ID",									"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Application_Number",						"datatype" : "VARCHAR PRIMARY KEY",			"objdefault" :''},
			{"name" : "Selfi_Video_Path",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Personal_Video_Path",					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Selfi_Video_Status",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Personal_Video_Status",					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Selfi_Video_SyncStatus",					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Personal_Video_SyncStatus",				"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Added_By",								"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Selfie_Camera_Available",				"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Added_On",								"datatype" : "DATETIME",					"objdefault" :''},
			{"name" : "PIVC_Medical_Qs_Ans_Flag",				"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Cust_Salutation",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Cust_Name",								"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Cust_Email_ID",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Cust_Mobile_Number",						"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Cust_Contact_Number",					"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Cust_Message",							"datatype" : "VARCHAR",						"objdefault" : ''},
			{"name" : "Scheduled_Date",							"datatype" : "DATETIME",					"objdefault" : ''},
			{"name" : "iscompleted",							"datatype" : "VARCHAR(10)",					"objdefault" : '0'},
			{"name" : "issync",									"datatype" : "VARCHAR(10)",					"objdefault" : '0'}
		],
	"Attendance_Emp_DailyAtt":[
			{"name" : "Address",					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Device_Id",			        "datatype" : "VARCHAR",		            	"objdefault" :''},
			{"name" : "InOut",						"datatype" : "VARCHAR",			     		"objdefault" :''},
			{"name" : "Latitude",					"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Longitude",			    	"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "SAP_Code",			    	"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Source_From",				"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "ischeckin",			    	"datatype" : "VARCHAR",						"objdefault" :'0'},
			{"name" : "ischeckout",			    	"datatype" : "VARCHAR",						"objdefault" :'0'},
		   	{"name" : "Login_DateTime",			    "datatype" : "DATETIME",					"objdefault" :''}
		],
	"shTpdData":[
		{"name" : "Txn_ID",						"datatype" : "NUMBER PRIMARY KEY",			"objdefault" : ''},
		{"name" : "ADVISORCODE",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ADVISORSTATUS",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ADVISORNAME",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CSC_CODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "SM_STATUS",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "SM_EMPCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "SM_NAME",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DOJ",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DESIGNATION_OF_LEADER",		"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CHANNEL",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "LOCATION_CODE",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "LOCATION",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CHANNEL_PARTNER",			"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CHANNELPARTNER_NAME",		"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "COMPANY_UNITCODE",			"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "COMPANY_UNITNAME",			"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "BM_EMPCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "BM_NAME",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CM_EMPCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CM_NAME",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "RM_EMPCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "RM_NAME",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "REGION",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DIRECTMGRCODE",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DIRECT_STATUS",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DIRECT_NAME",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DIRECT_TYPE",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "DIRECT_EMPCODE",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "COMPANY_LOCATION",			"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "COMPANY_LOCATION_DESC",		"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ADVISORDESIGNTAION",			"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ADVISORTYPE",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CHANNEL_MST",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CHANNEL_MST_NAME",			"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "FLAG",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "SERVPROVDINFO",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ZM_EMPCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ZM_NAME",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "ZONE",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "AO_EMPCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "AO_NAME",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "AREA",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "AOMGRCODE",					"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CMCODE",						"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CLUSTER_NAME",				"datatype" : "VARCHAR",						"objdefault" : ''},
		{"name" : "CMMGRCODE",					"datatype" : "VARCHAR",						"objdefault" : ''}
		],
	"superTrackAlerts":[
			{"name" : "Type",							"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "Alert",							"datatype" : "VARCHAR PRIMARY KEY",			"objdefault" :''},
			{"name" : "PressID",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "NewsDate",						"datatype" : "VARCHAR",						"objdefault" :''},
			{"name" : "iscompleted",					"datatype" : "VARCHAR",						"objdefault" : '0'},
			{"name" : "issync",							"datatype" : "VARCHAR",						"objdefault" : '0'}
		],
};

