/**
 * priorityOrder.js
 * @author CloudPact Technologies
 * @description : This script is used giving value based on income level,citytier and needs
 **/
var priorityOrder_json=[
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buying a House",
        "Key": "MediumTier I/MetroBuying a House",
        "Single": "",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Buying a House",
        "Key": "MediumTier IIBuying a House",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Buying a House",
        "Key": "MediumTier IIIBuying a House",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buying a House",
        "Key": "HighTier I/MetroBuying a House",
        "Single": "",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Buying a House",
        "Key": "HighTier IIBuying a House",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Buying a House",
        "Key": "HighTier IIIBuying a House",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buying a House",
        "Key": "LowTier I/MetroBuying a House",
        "Single": "",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Buying a House",
        "Key": "LowTier IIBuying a House",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Buying a House",
        "Key": "LowTier IIIBuying a House",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "MediumTier I/MetroChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "MediumTier IIChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "MediumTier IIIChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "HighTier I/MetroChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "HighTier IIChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "HighTier IIIChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "LowTier I/MetroChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "LowTier IIChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "LowTier IIIChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "MediumTier I/MetroChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": " 1 ",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "MediumTier IIChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "MediumTier IIIChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "HighTier I/MetroChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "HighTier IIChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "HighTier IIIChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "LowTier I/MetroChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "LowTier IIChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "LowTier IIIChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Health -Family",
        "Key": "MediumTier I/MetroHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Health -Family",
        "Key": "MediumTier IIHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Health -Family",
        "Key": "MediumTier IIIHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Health -Family",
        "Key": "HighTier I/MetroHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Health -Family",
        "Key": "HighTier IIHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Health -Family",
        "Key": "HighTier IIIHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Health -Family",
        "Key": "LowTier I/MetroHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Health -Family",
        "Key": "LowTier IIHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Health -Family",
        "Key": "LowTier IIIHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Legacy",
        "Key": "MediumTier I/MetroLegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Legacy",
        "Key": "MediumTier IILegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Legacy",
        "Key": "MediumTier IIILegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Legacy",
        "Key": "HighTier I/MetroLegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Legacy",
        "Key": "HighTier IILegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Legacy",
        "Key": "HighTier IIILegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Legacy",
        "Key": "LowTier I/MetroLegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Legacy",
        "Key": "LowTier IILegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Legacy",
        "Key": "LowTier IIILegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Liquidity",
        "Key": "MediumTier I/MetroLiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Liquidity",
        "Key": "MediumTier IILiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Liquidity",
        "Key": "MediumTier IIILiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Liquidity",
        "Key": "HighTier I/MetroLiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Liquidity",
        "Key": "HighTier IILiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Liquidity",
        "Key": "HighTier IIILiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Liquidity",
        "Key": "LowTier I/MetroLiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Liquidity",
        "Key": "LowTier IILiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Liquidity",
        "Key": "LowTier IIILiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "MediumTier I/MetroLiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "MediumTier IILiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "MediumTier IIILiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "HighTier I/MetroLiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "HighTier IILiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "HighTier IIILiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "LowTier I/MetroLiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "LowTier IILiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "LowTier IIILiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "MediumTier I/MetroBuy/Change Car",
        "Single": "3",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "MediumTier IIBuy/Change Car",
        "Single": "",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "MediumTier IIIBuy/Change Car",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "HighTier I/MetroBuy/Change Car",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "3",
        "Retiree": "3"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "HighTier IIBuy/Change Car",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "3",
        "Retiree": "3"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "HighTier IIIBuy/Change Car",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "3",
        "Retiree": "3"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "LowTier I/MetroBuy/Change Car",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "LowTier IIBuy/Change Car",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "LowTier IIIBuy/Change Car",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Renovation",
        "Key": "MediumTier I/MetroRenovation",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Renovation",
        "Key": "MediumTier IIRenovation",
        "Single": "1",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Renovation",
        "Key": "MediumTier IIIRenovation",
        "Single": "1",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Renovation",
        "Key": "HighTier I/MetroRenovation",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Renovation",
        "Key": "HighTier IIRenovation",
        "Single": "1",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Renovation",
        "Key": "HighTier IIIRenovation",
        "Single": "1",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Renovation",
        "Key": "LowTier I/MetroRenovation",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Renovation",
        "Key": "LowTier IIRenovation",
        "Single": "1",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Renovation",
        "Key": "LowTier IIIRenovation",
        "Single": "1",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Retirement",
        "Key": "MediumTier I/MetroRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Retirement",
        "Key": "MediumTier IIRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Retirement",
        "Key": "MediumTier IIIRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Retirement",
        "Key": "HighTier I/MetroRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Retirement",
        "Key": "HighTier IIRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Retirement",
        "Key": "HighTier IIIRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Retirement",
        "Key": "LowTier I/MetroRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Retirement",
        "Key": "LowTier IIRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Retirement",
        "Key": "LowTier IIIRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Second house",
        "Key": "MediumTier I/MetroSecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Second house",
        "Key": "MediumTier IISecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Second house",
        "Key": "MediumTier IIISecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "3",
        "Married with grown up child": "3",
        "Nearing Retirement": "3",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Second house",
        "Key": "HighTier I/MetroSecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Second house",
        "Key": "HighTier IISecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Second house",
        "Key": "HighTier IIISecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "3",
        "Married with grown up child": "3",
        "Nearing Retirement": "3",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Second house",
        "Key": "LowTier I/MetroSecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Second house",
        "Key": "LowTier IISecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Second house",
        "Key": "LowTier IIISecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "MediumTier I/MetroPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "MediumTier IIPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "MediumTier IIIPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "HighTier I/MetroPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "HighTier IIPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "HighTier IIIPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "LowTier I/MetroPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "LowTier IIPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "LowTier IIIPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "MediumTier I/MetroStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "MediumTier IIStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "MediumTier IIIStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "HighTier I/MetroStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "HighTier IIStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "HighTier IIIStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "LowTier I/MetroStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "LowTier IIStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "LowTier IIIStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "MediumTier I/MetroVacation/Festivities",
        "Single": "1",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "MediumTier IIVacation/Festivities",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "MediumTier IIIVacation/Festivities",
        "Single": "",
        "Married": "2",
        "Married with young kid/s": "3",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "HighTier I/MetroVacation/Festivities",
        "Single": "1",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "HighTier IIVacation/Festivities",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "High",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "HighTier IIIVacation/Festivities",
        "Single": "",
        "Married": "2",
        "Married with young kid/s": "3",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "LowTier I/MetroVacation/Festivities",
        "Single": "1",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier II",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "LowTier IIVacation/Festivities",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "Low",
        "City Category": "Tier III",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "LowTier IIIVacation/Festivities",
        "Single": "",
        "Married": "2",
        "Married with young kid/s": "3",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buying a House",
        "Key": "Medium to HighTier I/MetroBuying a House",
        "Single": "",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Higher Education",
        "Key": "Medium to HighTier I/MetroChild's Higher Education",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Child's Marriage",
        "Key": "Medium to HighTier I/MetroChild's Marriage",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Health -Family",
        "Key": "Medium to HighTier I/MetroHealth -Family",
        "Single": "3",
        "Married": "3",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Legacy",
        "Key": "Medium to HighTier I/MetroLegacy",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Liquidity",
        "Key": "Medium to HighTier I/MetroLiquidity",
        "Single": "2",
        "Married": "2",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Living Expenses",
        "Key": "Medium to HighTier I/MetroLiving Expenses",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "2",
        "Retiree": "2"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Buy/Change Car",
        "Key": "Medium to HighTier I/MetroBuy/Change Car",
        "Single": "2",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "3",
        "Retiree": "3"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Renovation",
        "Key": "Medium to HighTier I/MetroRenovation",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "1",
        "Retiree": "1"
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Retirement",
        "Key": "Medium to HighTier I/MetroRetirement",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "1",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Second house",
        "Key": "Medium to HighTier I/MetroSecond house",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Pure Protection Cover",
        "Key": "Medium to HighTier I/MetroPure Protection Cover",
        "Single": "1",
        "Married": "1",
        "Married with young kid/s": "1",
        "Married with growing kid/s": "1",
        "Married with grown up child": "1",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Start-up Capital",
        "Key": "Medium to HighTier I/MetroStart-up Capital",
        "Single": "",
        "Married": "",
        "Married with young kid/s": "",
        "Married with growing kid/s": "",
        "Married with grown up child": "",
        "Nearing Retirement": "",
        "Retiree": ""
    },
    {
        "Income Level": "Medium to High",
        "City Category": "Tier I/Metro",
        "Need/Expenses Revised": "Vacation/Festivities",
        "Key": "Medium to HighTier I/MetroVacation/Festivities",
        "Single": "1",
        "Married": "2",
        "Married with young kid/s": "2",
        "Married with growing kid/s": "2",
        "Married with grown up child": "2",
        "Nearing Retirement": "2",
        "Retiree": "1"
    }
];